//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAVECinema.cinema {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webServer/", ConfigurationName="cinema.CinemaWebServer")]
    public interface CinemaWebServer {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webServer/CinemaWebServer/getManagerRequest", ReplyAction="http://webServer/CinemaWebServer/getManagerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestAVECinema.cinema.getManagerResponse getManager(TestAVECinema.cinema.getManagerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServer/CinemaWebServer/getManagerRequest", ReplyAction="http://webServer/CinemaWebServer/getManagerResponse")]
        System.Threading.Tasks.Task<TestAVECinema.cinema.getManagerResponse> getManagerAsync(TestAVECinema.cinema.getManagerRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webServer/CinemaWebServer/logInRequest", ReplyAction="http://webServer/CinemaWebServer/logInResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestAVECinema.cinema.logInResponse logIn(TestAVECinema.cinema.logInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServer/CinemaWebServer/logInRequest", ReplyAction="http://webServer/CinemaWebServer/logInResponse")]
        System.Threading.Tasks.Task<TestAVECinema.cinema.logInResponse> logInAsync(TestAVECinema.cinema.logInRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webServer/CinemaWebServer/getCustomerRequest", ReplyAction="http://webServer/CinemaWebServer/getCustomerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestAVECinema.cinema.getCustomerResponse getCustomer(TestAVECinema.cinema.getCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServer/CinemaWebServer/getCustomerRequest", ReplyAction="http://webServer/CinemaWebServer/getCustomerResponse")]
        System.Threading.Tasks.Task<TestAVECinema.cinema.getCustomerResponse> getCustomerAsync(TestAVECinema.cinema.getCustomerRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webServer/CinemaWebServer/saveMovieRequest", ReplyAction="http://webServer/CinemaWebServer/saveMovieResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestAVECinema.cinema.saveMovieResponse saveMovie(TestAVECinema.cinema.saveMovieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServer/CinemaWebServer/saveMovieRequest", ReplyAction="http://webServer/CinemaWebServer/saveMovieResponse")]
        System.Threading.Tasks.Task<TestAVECinema.cinema.saveMovieResponse> saveMovieAsync(TestAVECinema.cinema.saveMovieRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webServer/CinemaWebServer/updateMovieInfoRequest", ReplyAction="http://webServer/CinemaWebServer/updateMovieInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestAVECinema.cinema.updateMovieInfoResponse updateMovieInfo(TestAVECinema.cinema.updateMovieInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServer/CinemaWebServer/updateMovieInfoRequest", ReplyAction="http://webServer/CinemaWebServer/updateMovieInfoResponse")]
        System.Threading.Tasks.Task<TestAVECinema.cinema.updateMovieInfoResponse> updateMovieInfoAsync(TestAVECinema.cinema.updateMovieInfoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webServer/CinemaWebServer/getAllMoviesRequest", ReplyAction="http://webServer/CinemaWebServer/getAllMoviesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestAVECinema.cinema.getAllMoviesResponse getAllMovies(TestAVECinema.cinema.getAllMoviesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServer/CinemaWebServer/getAllMoviesRequest", ReplyAction="http://webServer/CinemaWebServer/getAllMoviesResponse")]
        System.Threading.Tasks.Task<TestAVECinema.cinema.getAllMoviesResponse> getAllMoviesAsync(TestAVECinema.cinema.getAllMoviesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webServer/CinemaWebServer/getSchedulesRequest", ReplyAction="http://webServer/CinemaWebServer/getSchedulesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestAVECinema.cinema.getSchedulesResponse getSchedules(TestAVECinema.cinema.getSchedulesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServer/CinemaWebServer/getSchedulesRequest", ReplyAction="http://webServer/CinemaWebServer/getSchedulesResponse")]
        System.Threading.Tasks.Task<TestAVECinema.cinema.getSchedulesResponse> getSchedulesAsync(TestAVECinema.cinema.getSchedulesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webServer/CinemaWebServer/saveScheduleRequest", ReplyAction="http://webServer/CinemaWebServer/saveScheduleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestAVECinema.cinema.saveScheduleResponse saveSchedule(TestAVECinema.cinema.saveScheduleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServer/CinemaWebServer/saveScheduleRequest", ReplyAction="http://webServer/CinemaWebServer/saveScheduleResponse")]
        System.Threading.Tasks.Task<TestAVECinema.cinema.saveScheduleResponse> saveScheduleAsync(TestAVECinema.cinema.saveScheduleRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webServer/CinemaWebServer/updateManagerInfoRequest", ReplyAction="http://webServer/CinemaWebServer/updateManagerInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestAVECinema.cinema.updateManagerInfoResponse updateManagerInfo(TestAVECinema.cinema.updateManagerInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServer/CinemaWebServer/updateManagerInfoRequest", ReplyAction="http://webServer/CinemaWebServer/updateManagerInfoResponse")]
        System.Threading.Tasks.Task<TestAVECinema.cinema.updateManagerInfoResponse> updateManagerInfoAsync(TestAVECinema.cinema.updateManagerInfoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webServer/CinemaWebServer/updateCustomerInfoRequest", ReplyAction="http://webServer/CinemaWebServer/updateCustomerInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestAVECinema.cinema.updateCustomerInfoResponse updateCustomerInfo(TestAVECinema.cinema.updateCustomerInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServer/CinemaWebServer/updateCustomerInfoRequest", ReplyAction="http://webServer/CinemaWebServer/updateCustomerInfoResponse")]
        System.Threading.Tasks.Task<TestAVECinema.cinema.updateCustomerInfoResponse> updateCustomerInfoAsync(TestAVECinema.cinema.updateCustomerInfoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webServer/CinemaWebServer/registerNewCustomerRequest", ReplyAction="http://webServer/CinemaWebServer/registerNewCustomerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestAVECinema.cinema.registerNewCustomerResponse registerNewCustomer(TestAVECinema.cinema.registerNewCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServer/CinemaWebServer/registerNewCustomerRequest", ReplyAction="http://webServer/CinemaWebServer/registerNewCustomerResponse")]
        System.Threading.Tasks.Task<TestAVECinema.cinema.registerNewCustomerResponse> registerNewCustomerAsync(TestAVECinema.cinema.registerNewCustomerRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webServer/")]
    public partial class manager : user {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(manager))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(customer))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webServer/")]
    public abstract partial class user : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailField;
        
        private string passwordField;
        
        private string roleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
                this.RaisePropertyChanged("role");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webServer/")]
    public partial class voucher : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private int percentageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int percentage {
            get {
                return this.percentageField;
            }
            set {
                this.percentageField = value;
                this.RaisePropertyChanged("percentage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webServer/")]
    public partial class reservation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private movie movieField;
        
        private int numberOfTicketField;
        
        private double totalPriceField;
        
        private voucher voucherField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public movie movie {
            get {
                return this.movieField;
            }
            set {
                this.movieField = value;
                this.RaisePropertyChanged("movie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int numberOfTicket {
            get {
                return this.numberOfTicketField;
            }
            set {
                this.numberOfTicketField = value;
                this.RaisePropertyChanged("numberOfTicket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double totalPrice {
            get {
                return this.totalPriceField;
            }
            set {
                this.totalPriceField = value;
                this.RaisePropertyChanged("totalPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public voucher voucher {
            get {
                return this.voucherField;
            }
            set {
                this.voucherField = value;
                this.RaisePropertyChanged("voucher");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webServer/")]
    public partial class movie : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string actorField;
        
        private string directorField;
        
        private string genreField;
        
        private string languageField;
        
        private int lenghtField;
        
        private string movieIDField;
        
        private string overviewField;
        
        private string posterUrlField;
        
        private double priceField;
        
        private schedule[] schedulesField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string actor {
            get {
                return this.actorField;
            }
            set {
                this.actorField = value;
                this.RaisePropertyChanged("actor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string director {
            get {
                return this.directorField;
            }
            set {
                this.directorField = value;
                this.RaisePropertyChanged("director");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string genre {
            get {
                return this.genreField;
            }
            set {
                this.genreField = value;
                this.RaisePropertyChanged("genre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int lenght {
            get {
                return this.lenghtField;
            }
            set {
                this.lenghtField = value;
                this.RaisePropertyChanged("lenght");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string movieID {
            get {
                return this.movieIDField;
            }
            set {
                this.movieIDField = value;
                this.RaisePropertyChanged("movieID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string overview {
            get {
                return this.overviewField;
            }
            set {
                this.overviewField = value;
                this.RaisePropertyChanged("overview");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string posterUrl {
            get {
                return this.posterUrlField;
            }
            set {
                this.posterUrlField = value;
                this.RaisePropertyChanged("posterUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("schedules", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public schedule[] schedules {
            get {
                return this.schedulesField;
            }
            set {
                this.schedulesField = value;
                this.RaisePropertyChanged("schedules");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webServer/")]
    public partial class schedule : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dateField;
        
        private string endTimeField;
        
        private string roomNoField;
        
        private scheduleEntry[] seatsField;
        
        private string startTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string endTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
                this.RaisePropertyChanged("endTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string roomNo {
            get {
                return this.roomNoField;
            }
            set {
                this.roomNoField = value;
                this.RaisePropertyChanged("roomNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public scheduleEntry[] seats {
            get {
                return this.seatsField;
            }
            set {
                this.seatsField = value;
                this.RaisePropertyChanged("seats");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string startTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
                this.RaisePropertyChanged("startTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webServer/")]
    public partial class scheduleEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int keyField;
        
        private bool keyFieldSpecified;
        
        private reservation valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool keySpecified {
            get {
                return this.keyFieldSpecified;
            }
            set {
                this.keyFieldSpecified = value;
                this.RaisePropertyChanged("keySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public reservation value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webServer/")]
    public partial class customer : user {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string phoneNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string phoneNo {
            get {
                return this.phoneNoField;
            }
            set {
                this.phoneNoField = value;
                this.RaisePropertyChanged("phoneNo");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getManager", WrapperNamespace="http://webServer/", IsWrapped=true)]
    public partial class getManagerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServer/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getManagerRequest() {
        }
        
        public getManagerRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getManagerResponse", WrapperNamespace="http://webServer/", IsWrapped=true)]
    public partial class getManagerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServer/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestAVECinema.cinema.manager @return;
        
        public getManagerResponse() {
        }
        
        public getManagerResponse(TestAVECinema.cinema.manager @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="logIn", WrapperNamespace="http://webServer/", IsWrapped=true)]
    public partial class logInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServer/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServer/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public logInRequest() {
        }
        
        public logInRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="logInResponse", WrapperNamespace="http://webServer/", IsWrapped=true)]
    public partial class logInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServer/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestAVECinema.cinema.user @return;
        
        public logInResponse() {
        }
        
        public logInResponse(TestAVECinema.cinema.user @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustomer", WrapperNamespace="http://webServer/", IsWrapped=true)]
    public partial class getCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServer/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getCustomerRequest() {
        }
        
        public getCustomerRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustomerResponse", WrapperNamespace="http://webServer/", IsWrapped=true)]
    public partial class getCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServer/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestAVECinema.cinema.customer @return;
        
        public getCustomerResponse() {
        }
        
        public getCustomerResponse(TestAVECinema.cinema.customer @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveMovie", WrapperNamespace="http://webServer/", IsWrapped=true)]
    public partial class saveMovieRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServer/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestAVECinema.cinema.movie arg0;
        
        public saveMovieRequest() {
        }
        
        public saveMovieRequest(TestAVECinema.cinema.movie arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveMovieResponse", WrapperNamespace="http://webServer/", IsWrapped=true)]
    public partial class saveMovieResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServer/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public saveMovieResponse() {
        }
        
        public saveMovieResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateMovieInfo", WrapperNamespace="http://webServer/", IsWrapped=true)]
    public partial class updateMovieInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServer/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestAVECinema.cinema.movie arg0;
        
        public updateMovieInfoRequest() {
        }
        
        public updateMovieInfoRequest(TestAVECinema.cinema.movie arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateMovieInfoResponse", WrapperNamespace="http://webServer/", IsWrapped=true)]
    public partial class updateMovieInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServer/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public updateMovieInfoResponse() {
        }
        
        public updateMovieInfoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllMovies", WrapperNamespace="http://webServer/", IsWrapped=true)]
    public partial class getAllMoviesRequest {
        
        public getAllMoviesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllMoviesResponse", WrapperNamespace="http://webServer/", IsWrapped=true)]
    public partial class getAllMoviesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServer/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestAVECinema.cinema.movie[] @return;
        
        public getAllMoviesResponse() {
        }
        
        public getAllMoviesResponse(TestAVECinema.cinema.movie[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSchedules", WrapperNamespace="http://webServer/", IsWrapped=true)]
    public partial class getSchedulesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServer/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getSchedulesRequest() {
        }
        
        public getSchedulesRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSchedulesResponse", WrapperNamespace="http://webServer/", IsWrapped=true)]
    public partial class getSchedulesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServer/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestAVECinema.cinema.schedule[] @return;
        
        public getSchedulesResponse() {
        }
        
        public getSchedulesResponse(TestAVECinema.cinema.schedule[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveSchedule", WrapperNamespace="http://webServer/", IsWrapped=true)]
    public partial class saveScheduleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServer/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestAVECinema.cinema.schedule arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServer/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public saveScheduleRequest() {
        }
        
        public saveScheduleRequest(TestAVECinema.cinema.schedule arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveScheduleResponse", WrapperNamespace="http://webServer/", IsWrapped=true)]
    public partial class saveScheduleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServer/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public saveScheduleResponse() {
        }
        
        public saveScheduleResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateManagerInfo", WrapperNamespace="http://webServer/", IsWrapped=true)]
    public partial class updateManagerInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServer/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestAVECinema.cinema.manager arg0;
        
        public updateManagerInfoRequest() {
        }
        
        public updateManagerInfoRequest(TestAVECinema.cinema.manager arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateManagerInfoResponse", WrapperNamespace="http://webServer/", IsWrapped=true)]
    public partial class updateManagerInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServer/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public updateManagerInfoResponse() {
        }
        
        public updateManagerInfoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateCustomerInfo", WrapperNamespace="http://webServer/", IsWrapped=true)]
    public partial class updateCustomerInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServer/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestAVECinema.cinema.customer arg0;
        
        public updateCustomerInfoRequest() {
        }
        
        public updateCustomerInfoRequest(TestAVECinema.cinema.customer arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateCustomerInfoResponse", WrapperNamespace="http://webServer/", IsWrapped=true)]
    public partial class updateCustomerInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServer/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public updateCustomerInfoResponse() {
        }
        
        public updateCustomerInfoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerNewCustomer", WrapperNamespace="http://webServer/", IsWrapped=true)]
    public partial class registerNewCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServer/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestAVECinema.cinema.customer arg0;
        
        public registerNewCustomerRequest() {
        }
        
        public registerNewCustomerRequest(TestAVECinema.cinema.customer arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerNewCustomerResponse", WrapperNamespace="http://webServer/", IsWrapped=true)]
    public partial class registerNewCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServer/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public registerNewCustomerResponse() {
        }
        
        public registerNewCustomerResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CinemaWebServerChannel : TestAVECinema.cinema.CinemaWebServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CinemaWebServerClient : System.ServiceModel.ClientBase<TestAVECinema.cinema.CinemaWebServer>, TestAVECinema.cinema.CinemaWebServer {
        
        public CinemaWebServerClient() {
        }
        
        public CinemaWebServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CinemaWebServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CinemaWebServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CinemaWebServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAVECinema.cinema.getManagerResponse TestAVECinema.cinema.CinemaWebServer.getManager(TestAVECinema.cinema.getManagerRequest request) {
            return base.Channel.getManager(request);
        }
        
        public TestAVECinema.cinema.manager getManager(string arg0) {
            TestAVECinema.cinema.getManagerRequest inValue = new TestAVECinema.cinema.getManagerRequest();
            inValue.arg0 = arg0;
            TestAVECinema.cinema.getManagerResponse retVal = ((TestAVECinema.cinema.CinemaWebServer)(this)).getManager(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestAVECinema.cinema.getManagerResponse> TestAVECinema.cinema.CinemaWebServer.getManagerAsync(TestAVECinema.cinema.getManagerRequest request) {
            return base.Channel.getManagerAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestAVECinema.cinema.getManagerResponse> getManagerAsync(string arg0) {
            TestAVECinema.cinema.getManagerRequest inValue = new TestAVECinema.cinema.getManagerRequest();
            inValue.arg0 = arg0;
            return ((TestAVECinema.cinema.CinemaWebServer)(this)).getManagerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAVECinema.cinema.logInResponse TestAVECinema.cinema.CinemaWebServer.logIn(TestAVECinema.cinema.logInRequest request) {
            return base.Channel.logIn(request);
        }
        
        public TestAVECinema.cinema.user logIn(string arg0, string arg1) {
            TestAVECinema.cinema.logInRequest inValue = new TestAVECinema.cinema.logInRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            TestAVECinema.cinema.logInResponse retVal = ((TestAVECinema.cinema.CinemaWebServer)(this)).logIn(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestAVECinema.cinema.logInResponse> TestAVECinema.cinema.CinemaWebServer.logInAsync(TestAVECinema.cinema.logInRequest request) {
            return base.Channel.logInAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestAVECinema.cinema.logInResponse> logInAsync(string arg0, string arg1) {
            TestAVECinema.cinema.logInRequest inValue = new TestAVECinema.cinema.logInRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((TestAVECinema.cinema.CinemaWebServer)(this)).logInAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAVECinema.cinema.getCustomerResponse TestAVECinema.cinema.CinemaWebServer.getCustomer(TestAVECinema.cinema.getCustomerRequest request) {
            return base.Channel.getCustomer(request);
        }
        
        public TestAVECinema.cinema.customer getCustomer(string arg0) {
            TestAVECinema.cinema.getCustomerRequest inValue = new TestAVECinema.cinema.getCustomerRequest();
            inValue.arg0 = arg0;
            TestAVECinema.cinema.getCustomerResponse retVal = ((TestAVECinema.cinema.CinemaWebServer)(this)).getCustomer(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestAVECinema.cinema.getCustomerResponse> TestAVECinema.cinema.CinemaWebServer.getCustomerAsync(TestAVECinema.cinema.getCustomerRequest request) {
            return base.Channel.getCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestAVECinema.cinema.getCustomerResponse> getCustomerAsync(string arg0) {
            TestAVECinema.cinema.getCustomerRequest inValue = new TestAVECinema.cinema.getCustomerRequest();
            inValue.arg0 = arg0;
            return ((TestAVECinema.cinema.CinemaWebServer)(this)).getCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAVECinema.cinema.saveMovieResponse TestAVECinema.cinema.CinemaWebServer.saveMovie(TestAVECinema.cinema.saveMovieRequest request) {
            return base.Channel.saveMovie(request);
        }
        
        public bool saveMovie(TestAVECinema.cinema.movie arg0) {
            TestAVECinema.cinema.saveMovieRequest inValue = new TestAVECinema.cinema.saveMovieRequest();
            inValue.arg0 = arg0;
            TestAVECinema.cinema.saveMovieResponse retVal = ((TestAVECinema.cinema.CinemaWebServer)(this)).saveMovie(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestAVECinema.cinema.saveMovieResponse> TestAVECinema.cinema.CinemaWebServer.saveMovieAsync(TestAVECinema.cinema.saveMovieRequest request) {
            return base.Channel.saveMovieAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestAVECinema.cinema.saveMovieResponse> saveMovieAsync(TestAVECinema.cinema.movie arg0) {
            TestAVECinema.cinema.saveMovieRequest inValue = new TestAVECinema.cinema.saveMovieRequest();
            inValue.arg0 = arg0;
            return ((TestAVECinema.cinema.CinemaWebServer)(this)).saveMovieAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAVECinema.cinema.updateMovieInfoResponse TestAVECinema.cinema.CinemaWebServer.updateMovieInfo(TestAVECinema.cinema.updateMovieInfoRequest request) {
            return base.Channel.updateMovieInfo(request);
        }
        
        public bool updateMovieInfo(TestAVECinema.cinema.movie arg0) {
            TestAVECinema.cinema.updateMovieInfoRequest inValue = new TestAVECinema.cinema.updateMovieInfoRequest();
            inValue.arg0 = arg0;
            TestAVECinema.cinema.updateMovieInfoResponse retVal = ((TestAVECinema.cinema.CinemaWebServer)(this)).updateMovieInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestAVECinema.cinema.updateMovieInfoResponse> TestAVECinema.cinema.CinemaWebServer.updateMovieInfoAsync(TestAVECinema.cinema.updateMovieInfoRequest request) {
            return base.Channel.updateMovieInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestAVECinema.cinema.updateMovieInfoResponse> updateMovieInfoAsync(TestAVECinema.cinema.movie arg0) {
            TestAVECinema.cinema.updateMovieInfoRequest inValue = new TestAVECinema.cinema.updateMovieInfoRequest();
            inValue.arg0 = arg0;
            return ((TestAVECinema.cinema.CinemaWebServer)(this)).updateMovieInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAVECinema.cinema.getAllMoviesResponse TestAVECinema.cinema.CinemaWebServer.getAllMovies(TestAVECinema.cinema.getAllMoviesRequest request) {
            return base.Channel.getAllMovies(request);
        }
        
        public TestAVECinema.cinema.movie[] getAllMovies() {
            TestAVECinema.cinema.getAllMoviesRequest inValue = new TestAVECinema.cinema.getAllMoviesRequest();
            TestAVECinema.cinema.getAllMoviesResponse retVal = ((TestAVECinema.cinema.CinemaWebServer)(this)).getAllMovies(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestAVECinema.cinema.getAllMoviesResponse> TestAVECinema.cinema.CinemaWebServer.getAllMoviesAsync(TestAVECinema.cinema.getAllMoviesRequest request) {
            return base.Channel.getAllMoviesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestAVECinema.cinema.getAllMoviesResponse> getAllMoviesAsync() {
            TestAVECinema.cinema.getAllMoviesRequest inValue = new TestAVECinema.cinema.getAllMoviesRequest();
            return ((TestAVECinema.cinema.CinemaWebServer)(this)).getAllMoviesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAVECinema.cinema.getSchedulesResponse TestAVECinema.cinema.CinemaWebServer.getSchedules(TestAVECinema.cinema.getSchedulesRequest request) {
            return base.Channel.getSchedules(request);
        }
        
        public TestAVECinema.cinema.schedule[] getSchedules(string arg0) {
            TestAVECinema.cinema.getSchedulesRequest inValue = new TestAVECinema.cinema.getSchedulesRequest();
            inValue.arg0 = arg0;
            TestAVECinema.cinema.getSchedulesResponse retVal = ((TestAVECinema.cinema.CinemaWebServer)(this)).getSchedules(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestAVECinema.cinema.getSchedulesResponse> TestAVECinema.cinema.CinemaWebServer.getSchedulesAsync(TestAVECinema.cinema.getSchedulesRequest request) {
            return base.Channel.getSchedulesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestAVECinema.cinema.getSchedulesResponse> getSchedulesAsync(string arg0) {
            TestAVECinema.cinema.getSchedulesRequest inValue = new TestAVECinema.cinema.getSchedulesRequest();
            inValue.arg0 = arg0;
            return ((TestAVECinema.cinema.CinemaWebServer)(this)).getSchedulesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAVECinema.cinema.saveScheduleResponse TestAVECinema.cinema.CinemaWebServer.saveSchedule(TestAVECinema.cinema.saveScheduleRequest request) {
            return base.Channel.saveSchedule(request);
        }
        
        public int saveSchedule(TestAVECinema.cinema.schedule arg0, string arg1) {
            TestAVECinema.cinema.saveScheduleRequest inValue = new TestAVECinema.cinema.saveScheduleRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            TestAVECinema.cinema.saveScheduleResponse retVal = ((TestAVECinema.cinema.CinemaWebServer)(this)).saveSchedule(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestAVECinema.cinema.saveScheduleResponse> TestAVECinema.cinema.CinemaWebServer.saveScheduleAsync(TestAVECinema.cinema.saveScheduleRequest request) {
            return base.Channel.saveScheduleAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestAVECinema.cinema.saveScheduleResponse> saveScheduleAsync(TestAVECinema.cinema.schedule arg0, string arg1) {
            TestAVECinema.cinema.saveScheduleRequest inValue = new TestAVECinema.cinema.saveScheduleRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((TestAVECinema.cinema.CinemaWebServer)(this)).saveScheduleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAVECinema.cinema.updateManagerInfoResponse TestAVECinema.cinema.CinemaWebServer.updateManagerInfo(TestAVECinema.cinema.updateManagerInfoRequest request) {
            return base.Channel.updateManagerInfo(request);
        }
        
        public bool updateManagerInfo(TestAVECinema.cinema.manager arg0) {
            TestAVECinema.cinema.updateManagerInfoRequest inValue = new TestAVECinema.cinema.updateManagerInfoRequest();
            inValue.arg0 = arg0;
            TestAVECinema.cinema.updateManagerInfoResponse retVal = ((TestAVECinema.cinema.CinemaWebServer)(this)).updateManagerInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestAVECinema.cinema.updateManagerInfoResponse> TestAVECinema.cinema.CinemaWebServer.updateManagerInfoAsync(TestAVECinema.cinema.updateManagerInfoRequest request) {
            return base.Channel.updateManagerInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestAVECinema.cinema.updateManagerInfoResponse> updateManagerInfoAsync(TestAVECinema.cinema.manager arg0) {
            TestAVECinema.cinema.updateManagerInfoRequest inValue = new TestAVECinema.cinema.updateManagerInfoRequest();
            inValue.arg0 = arg0;
            return ((TestAVECinema.cinema.CinemaWebServer)(this)).updateManagerInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAVECinema.cinema.updateCustomerInfoResponse TestAVECinema.cinema.CinemaWebServer.updateCustomerInfo(TestAVECinema.cinema.updateCustomerInfoRequest request) {
            return base.Channel.updateCustomerInfo(request);
        }
        
        public bool updateCustomerInfo(TestAVECinema.cinema.customer arg0) {
            TestAVECinema.cinema.updateCustomerInfoRequest inValue = new TestAVECinema.cinema.updateCustomerInfoRequest();
            inValue.arg0 = arg0;
            TestAVECinema.cinema.updateCustomerInfoResponse retVal = ((TestAVECinema.cinema.CinemaWebServer)(this)).updateCustomerInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestAVECinema.cinema.updateCustomerInfoResponse> TestAVECinema.cinema.CinemaWebServer.updateCustomerInfoAsync(TestAVECinema.cinema.updateCustomerInfoRequest request) {
            return base.Channel.updateCustomerInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestAVECinema.cinema.updateCustomerInfoResponse> updateCustomerInfoAsync(TestAVECinema.cinema.customer arg0) {
            TestAVECinema.cinema.updateCustomerInfoRequest inValue = new TestAVECinema.cinema.updateCustomerInfoRequest();
            inValue.arg0 = arg0;
            return ((TestAVECinema.cinema.CinemaWebServer)(this)).updateCustomerInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestAVECinema.cinema.registerNewCustomerResponse TestAVECinema.cinema.CinemaWebServer.registerNewCustomer(TestAVECinema.cinema.registerNewCustomerRequest request) {
            return base.Channel.registerNewCustomer(request);
        }
        
        public bool registerNewCustomer(TestAVECinema.cinema.customer arg0) {
            TestAVECinema.cinema.registerNewCustomerRequest inValue = new TestAVECinema.cinema.registerNewCustomerRequest();
            inValue.arg0 = arg0;
            TestAVECinema.cinema.registerNewCustomerResponse retVal = ((TestAVECinema.cinema.CinemaWebServer)(this)).registerNewCustomer(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestAVECinema.cinema.registerNewCustomerResponse> TestAVECinema.cinema.CinemaWebServer.registerNewCustomerAsync(TestAVECinema.cinema.registerNewCustomerRequest request) {
            return base.Channel.registerNewCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestAVECinema.cinema.registerNewCustomerResponse> registerNewCustomerAsync(TestAVECinema.cinema.customer arg0) {
            TestAVECinema.cinema.registerNewCustomerRequest inValue = new TestAVECinema.cinema.registerNewCustomerRequest();
            inValue.arg0 = arg0;
            return ((TestAVECinema.cinema.CinemaWebServer)(this)).registerNewCustomerAsync(inValue);
        }
    }
}
